name = "karpo-content-studio"
main = "./dist/_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[routes]]
pattern = "contentstudiokrp.es"
custom_domain = true

[[routes]]
pattern = "www.contentstudiokrp.es"
custom_domain = true
