name = "thecontentstudio"
compatibility_date = "2024-11-21"

# Configuración para Pages con Functions
pages_build_output_dir = "dist"

# Variables de entorno - configurar en Cloudflare Dashboard
# Dashboard > Pages > tu-proyecto > Settings > Environment Variables
# 
# Variables requeridas:
# PUBLIC_SUPABASE_URL
# PUBLIC_SUPABASE_ANON_KEY  
# SUPABASE_SERVICE_ROLE_KEY
# BILLIONMAIL_API_KEY
# BILLIONMAIL_FROM_EMAIL
# ADMIN_EMAIL
# ADMIN_PASSWORD
